### ISSUE TITLE
404 error for form submitting

### ISSUE THREAD

**Issue by o-tsaruk** [netlify-templates/next-platform-starter#24]
Hey! I've deployed this app to Netlify, and got the same error I faced with sending POST request to html form or static file.

![image](https://github.com/netlify-templates/next-platform-starter/assets/90980937/63656909-b000-47c2-9206-03a3ee27c62a)

What build settings do I need to use?

**Comment by TomasBankauskas** [comment]
Hey @o-tsaruk, thank you for reaching out. Did you [enable form detection](https://docs.netlify.com/forms/setup/#enable-form-detection) in Netlify dashboard?

**Comment by o-tsaruk** [comment]
Hey @TomasBankauskas . Yes, it's enabled.

**Comment by o-tsaruk** [comment]
I've enabled form detection before deployment and I thought that it should work. I ran the site build again today, and now the fork works. My bad.

**Comment by o-tsaruk** [comment]
@TomasBankauskas thank you for your time and responds :+1:

**Comment by TomasBankauskas** [comment]
Np, happy to help!

**Comment by davshoward** [comment]
I'm getting the same issue.

Page exists (can hit it directly), but the fetch throws a 404...

**Comment by Itisfilipe** [comment]
> I'm getting the same issue.
> 
> Page exists (can hit it directly), but the fetch throws a 404...
> 
> I can see the form in the UI, but not submissions possible.

I am having the same issue 🤔

**Comment by TomasBankauskas** [comment]
Hi @Itisfilipe, pls enable form detection in the Netlify dashboard and run the site build again.
